# Generated by Django 2.2.6 on 2020-05-14 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extra', '0002_feedback_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='from_email',
            field=models.EmailField(max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='subject',
            field=models.CharField(max_length=75, null=True),
        ),
    ]
