# Generated by Django 2.2.6 on 2020-05-14 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extra', '0003_auto_20200514_1801'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='from_email',
        ),
        migrations.AddField(
            model_name='feedback',
            name='name',
            field=models.CharField(max_length=75, null=True),
        ),
    ]
