# Generated by Django 2.2.6 on 2020-07-07 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OldnameNewnameTableLeft',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_2020', models.CharField(blank=True, max_length=250)),
                ('name_1998', models.CharField(blank=True, max_length=250)),
                ('alternative_name', models.CharField(blank=True, max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='OldnameNewnameTableRight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_2020', models.CharField(blank=True, max_length=250)),
                ('name_1998', models.CharField(blank=True, max_length=250)),
                ('alternative_name', models.CharField(blank=True, max_length=250)),
            ],
        ),
    ]
