# Generated by Django 2.2.5 on 2019-10-21 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pesticidalproteindatabase',
            options={},
        ),
    ]
